encoding: UTF-8

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"
year: 2016
url: "https://sendoh-akira.github.io" # the base hostname & protocol for your site
baseurl: ""
# gavatar头像及Favicon
gavatar : /assets/img/gavatar_2.png
favicon : /assets/img/favicon_2.png

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
gems: [jekyll-paginate]

# 作者信息
author:
  name: 武燕飞
  email: wuyanfeijob@163.com
  link: http://wuyanfeigithub.io/
  weibo: https://weibo.com/u/2726632531
  github: https://github.com/wuyanfeigithub
  github_username:  wuyanfeigithub
  zhihu:
  weibo_username:

# 站点信息
title: Sendoh Akira
description:

rss_url: /feed.xml


# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : 红衣佳人白衣友<br>朝与同歌暮同酒<br>世人谓我恋长安<br>其实只恋长安某<br><br><br>

# 首页除了最新文章外显示分类
cates:
- Essay
# - Python
# - OpenStack

# 不蒜子网站计数设置
# http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  switch: 1
  site_visit: 小伙伴到访数
  page_visit: 本页阅读量

# 中文本地化
locals:
   newest : 最新文章
