encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
gems: [jekyll-paginate]

# 作者信息
author: 
  name: 武燕飞
  email: wuyanfeijob@163.com
  link: http://wuyanfei.github.io/
  weibo: 
  github: https://github.com/wuyanfeigithub
  github_username:  wuyanfeigithub
  zhihu: 
  weibo_username:  

# 站点信息
title: 皇后镇
description: 
 If,<br>for example,<br>you come at four o'clock in the afternoon,<br>then at three o'clock I shall begin to be happy.
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : 含泪奔跑<br>华丽跌倒<br>人山人海<br>边走边爱<br><br>

# 首页除了最新文章外显示分类
cates: 
- Essay
# - Python
# - OpenStack

# 中文本地化
locals: 
   newest : 最新文章
